title: nʇʞn's Blog
iconURL: assets/default-icon.png
theme: blog

# for a clean URL
permalink: :slug

markdown: kramdown
kramdown:
   math_engine: mathjax


social:
  twitter: Rhotav
  github: Rhotav

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
